<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><LangVersion>latest</LangVersion><RootNamespace>FluNET.Classic.Secrets.Azure</RootNamespace><AssemblyName>FluNET.Classic.Secrets.Azure</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../../../Engine/FluNET.Classic.Core/FluNET.Classic.Core.csproj" /><ProjectReference Include="../FluNET.Classic.Secrets/FluNET.Classic.Secrets.csproj" /></ItemGroup></Project>