<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>FluNET.Classic.Runtime</RootNamespace>
    <AssemblyName>FluNET.Classic.Runtime</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FluNET.Classic.Core/FluNET.Classic.Core.csproj" />
    <ProjectReference Include="../FluNET.Classic.Syntax/FluNET.Classic.Syntax.csproj" />
    <ProjectReference Include="../FluNET.Classic.Binding/FluNET.Classic.Binding.csproj" />
  </ItemGroup>
</Project>
