<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><LangVersion>latest</LangVersion><RootNamespace>FluNET.Classic.Sql.PostgreSql</RootNamespace><AssemblyName>FluNET.Classic.Sql.PostgreSql</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../../../Engine/FluNET.Classic.Core/FluNET.Classic.Core.csproj" /><ProjectReference Include="../FluNET.Classic.Sql/FluNET.Classic.Sql.csproj" /></ItemGroup></Project>