[CmdletBinding()]
param(
    [string] $ChangelogPath = (Join-Path (Get-Location) "CHANGELOG.md"),
    [string] $OutputPath = (Join-Path (Get-Location) "docs\RELEASE-NOTES-0.2.md")
)

$changelog = Get-Content -LiteralPath $ChangelogPath -Raw
$match = [regex]::Match($changelog, '(?ms)^## \[Unreleased\]\r?\n(?<body>.*?)(?=^## \[)')
if (-not $match.Success) {
    throw "The changelog does not contain an [Unreleased] section."
}

$body = $match.Groups['body'].Value.Trim()
$notes = @(
    '# FluNET.Classic 0.2 release notes',
    '',
    '> Generated from the `[Unreleased]` section of `CHANGELOG.md`. Do not edit this file manually.',
    '',
    $body,
    ''
) -join [Environment]::NewLine

Set-Content -LiteralPath $OutputPath -Value $notes -Encoding utf8
Write-Output "Generated $OutputPath"
