name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore FluNET.sln
      - run: dotnet format FluNET.sln whitespace --no-restore --verify-no-changes
      - run: dotnet build FluNET.sln --configuration Release --no-restore
      - run: dotnet test FluNET.sln --configuration Release --no-build --verbosity normal
